---
suites:
  - name: default
    run_list:
      - recipe[osl-git::default]
  - name: git-credentials-databag
    run_list:
      - recipe[osl-git::default]
      - recipe[osl-git-test::databag]
    attributes:
      osl-git:
        secrets_databag: 'osl-git'
        secrets_item:    'item1'
  - name: git-credentials-attributes
    run_list:
      - recipe[osl-git::default]
      - recipe[osl-git-test::attributes]
    attributes:
      osl-git:
        secrets:
          credentials:
            - https://user:pass@example.net
            - ssh://foo:bar@example.org
            # Only has read access to empty test repo
            - https://gitlab+deploy-token-13:CWN8Fsjrtare7yAHkknj@git.osuosl.org
