name             'osl-git'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache-2.0'
chef_version     '>= 16.0'
issues_url       'https://github.com/osuosl-cookbooks/osl-git/issues'
source_url       'https://github.com/osuosl-cookbooks/osl-git'
description      'Installs/Configures osl-git'
version          '1.10.1'

depends          'git'
depends          'osl-resources'
depends          'osl-selinux'
depends          'yum-ius', '~> 3.1.0'

supports         'almalinux', '~> 8.0'
supports         'centos', '~> 7.0'
supports         'centos_stream', '~> 8.0'
