name             'osl-git-test'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache-2.0'
issues_url       'https://github.com/osuosl-cookbooks/osl-git-test/issues'
source_url       'https://github.com/osuosl-cookbooks/osl-git-test'
description      'Installs/Configures osl-git-test'
version          '0.1.0'

depends          'osl-git'
